name: Generate GitHub Art

on:
  push: {}           # 每次 push 時也會執行
  workflow_dispatch:  # 或手動觸發

jobs:
  commit-art:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 需要完整的 git 歷史才能正確推送 commit
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Run commit art script
        run: |
          chmod +x ./make_art.py
          python3 ./make_art.py
      - name: Configure Git and Push
        run: |
          git config --global user.email "your-email@example.com"
          git config --global user.name "Your Name"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
