name: Generate GitHub Art

on:
  push: {}
  workflow_dispatch:

jobs:
  commit-art:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true


      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Configure Git Identity
        run: |
          git config --global user.email "momolly1024@gmail.com"
          git config --global user.name "momolly1024"
          
      - name: Run commit art script
        run: |
          chmod +x ./make_art.py
          python3 ./make_art.py

      - name: Push changes
        run: git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
